{
  "phases": {
    "setup": {
      "nixPkgs": ["python311"]
    },
    "install": {
      "cmds": ["python3.11 -m venv /app/.venv", "source /app/.venv/bin/activate && pip install -r requirements.txt"]
    },
    "start": {
      "cmd": "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    }
  }
}
